import { Cloud, Code, Database, Globe, HelpCircle, Server } from "lucide-react";
import type { ProjectData, TechIconsMap } from "../../types";

export const techIcons: TechIconsMap = {
  React: Code,
  "Node.js": Server,
  JavaScript: Code,
  TypeScript: Code,
  MongoDB: Database,
  PostgreSQL: Database,
  MySQL: Database,
  Express: Server,
  "Next.js": Globe,
  "Vue.js": Code,
  AWS: Cloud,
  Docker: Server,
  Firebase: Cloud,
  Redux: Code,
  Tailwind: Globe,
  Bootstrap: Globe,
  Git: Code,
  Linux: Server,
  Nginx: Server,
  Redis: Database,
  "OpenAI API": HelpCircle,
  "Socket.io": HelpCircle,
  WebRTC: HelpCircle,
  "Chart.js": HelpCircle,
  "CoinGecko API": HelpCircle,
  TensorFlow: HelpCircle,
  "Stripe API": HelpCircle,
};

export const projectsData: ProjectData[] = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description:
      "A full-featured e-commerce platform with real-time inventory management, secure payment processing, and advanced analytics dashboard. Built with modern technologies for optimal performance and scalability.",
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Redux",
      "Stripe API",
    ],
    category: "Full Stack",
    year: "2024",
    status: "completed",
    featured: true,
    liveUrl: "https://demo-ecommerce.com",
    githubUrl: "https://github.com/username/ecommerce",
    // stats: { stars: 124, forks: 45, users: "2.5k" },
    features: [
      "Real-time inventory tracking",
      "Secure payment gateway integration",
      "Advanced analytics dashboard",
      "Multi-vendor support",
    ],
    image: "/",
  },
  {
    id: 2,
    title: "AI-Powered Task Manager",
    description:
      "Intelligent task management application with AI-driven priority suggestions, natural language processing for task creation, and smart deadline predictions.",
    technologies: [
      "Next.js",
      "TypeScript",
      "PostgreSQL",
      "OpenAI API",
      "TensorFlow",
    ],
    category: "AI/ML",
    year: "2024",
    status: "in-progress",
    githubUrl: "https://github.com/username/ai-taskmanager",
    // stats: { stars: 89, forks: 23 },
    features: [
      "AI-powered task prioritization",
      "Natural language task creation",
      "Smart deadline predictions",
      "Productivity insights",
    ],
    image: "/",
  },
  {
    id: 3,
    title: "Real-Time Chat Application",
    description:
      "Modern chat application with real-time messaging, file sharing, video calls, and end-to-end encryption. Supports group chats and custom emojis.",
    technologies: ["React", "Socket.io", "Node.js", "MongoDB", "WebRTC"],
    category: "Real-time",
    year: "2023",
    status: "completed",
    liveUrl: "https://chat-app-demo.com",
    githubUrl: "https://github.com/username/chat-app",
    // stats: { stars: 267, forks: 78, users: "5k" },
    features: [
      "Real-time messaging",
      "Video and voice calls",
      "End-to-end encryption",
      "File sharing support",
    ],
    image: "/",
  },
  {
    id: 4,
    title: "Cryptocurrency Tracker",
    description:
      "Comprehensive cryptocurrency tracking dashboard with real-time price updates, portfolio management, and advanced charting capabilities.",
    technologies: ["Vue.js", "Chart.js", "Express", "Redis", "CoinGecko API"],
    category: "Dashboard",
    year: "2023",
    status: "completed",
    liveUrl: "https://crypto-tracker-demo.com",
    githubUrl: "https://github.com/username/crypto-tracker",
    features: [
      "Real-time price tracking",
      "Portfolio management",
      "Advanced charting",
      "Price alerts",
    ],
    image: "/",
  },
  {
    id: 5,
    title: "Mobile Fitness App",
    description:
      "Cross-platform fitness application with workout tracking, nutrition logging, and social features for fitness enthusiasts.",
    technologies: ["Firebase", "Redux"],
    category: "Mobile",
    year: "2023",
    status: "completed",
    githubUrl: "https://github.com/username/fitness-app",
    // stats: { users: "1.2k" },
    features: [
      "Workout tracking",
      "Nutrition logging",
      "Social features",
      "Progress analytics",
    ],
    image: "/",
  },
  {
    id: 6,
    title: "DevOps Monitoring Dashboard",
    description:
      "Comprehensive monitoring solution for DevOps teams with real-time metrics, alerting system, and automated deployment tracking.",
    technologies: ["React", "Node.js", "Docker"],
    category: "DevOps",
    year: "2024",
    status: "in-progress",
    githubUrl: "https://github.com/username/devops-dashboard",
    features: [
      "Real-time system monitoring",
      "Automated alerting",
      "Deployment tracking",
      "Performance analytics",
    ],
    image: "/",
  },
];

export const categories = [
  "All",
  "Full Stack",
  "AI/ML",
  "Mobile",
  "Real-time",
  "Dashboard",
  "DevOps",
];
